[phases.setup]
nixPkgs = ["python3", "chromium"]

[phases.build]
cmds = [
    "python3 -m venv venv",
    ". venv/bin/activate && pip install -r api/requirements.txt",
    ". venv/bin/activate && playwright install chromium"
]

[start]
cmd = ". venv/bin/activate && cd api && uvicorn app:app --host 0.0.0.0 --port $PORT"
