[phases.setup]
nixPkgs = ["python3", "chromium"]

[phases.build]
cmds = ["cd api && python3 -m pip install -r requirements.txt", "cd api && python3 -m playwright install chromium"]

[start]
cmd = "cd api && python3 -m uvicorn app:app --host 0.0.0.0 --port $PORT"
